Repository wp-cli/language-command, pull requests merged in 2018-04, with the labels that each got.

#33 Fix PHP 5.3 memory issue
  .travis.yml
Labels: bug, scope:testing

#32 Updated wp language core update --dry-run message
  features/language-core.feature
  src/WP_CLI/CommandWithTranslation.php
Labels: command:language-core-update

#34 Update scaffolded files
  .gitignore
  README.md
  bin/test.sh
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/utils.php
  utils/behat-tags.php
Labels: scope:testing
